services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/configure.sh:/docker-entrypoint.d/99-geproxy-config.sh
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./pxe:/var/www/html
    ports:
      - "${PRIVATE_IP:-10.1.0.1}:80:80"
      - "${PRIVATE_IP:-10.1.0.1}:443:443"
    depends_on:
      devdocs:
        condition: service_started
      pixie:
        condition: service_started
      user-data:
        condition: service_completed_successfully
    environment:
      - CCS_HOST=${CCS_HOST:-https://judge.gehack.nl}
      - CONTEST_HASH=${CONTEST_HASH:-contest_hash}
      - SSL_CERT_LOC=${SSL_CERT_LOC:-}
      - SSL_KEY_LOC=${SSL_KEY_LOC:-}
      - DOMAIN=${DOMAIN:-progcont}
    cap_add:
      - NET_ADMIN

  acng:
    image: sameersbn/apt-cacher-ng:3.3-20200524
    volumes:
      - ./acng:/var/cache/apt-cacher-ng
    restart: always
    ports:
      - "${PRIVATE_IP:-10.1.0.1}:${ACNG_PORT:-3142}:3142"

  pixie:
    image: tuupke/pixie
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pixie:/geproxy
    ports:
      - ${PRIVATE_IP:-10.1.0.1}:5353:5353/udp
    environment:
      - DB_DSN=/geproxy/pixie.sqlite?cache=shared&mode=rwc
      - "CUPS_ADDR=${PRIVATE_IP:-10.1.0.1}:631"
      - LISTEN_ADDR=127.0.0.1:4000
    restart: always

  devdocs:
    image: geproxy/devdocs
    build:
      dockerfile: ./Dockerfile
      context: ./devdocs
    environment:
      - LANGUAGES="${LANGUAGES:-'openjdk@17 c cpp python@3.10'}"

  dnsmasq:
    image: geproxy/dnsmasq
    cap_add:
      - NET_ADMIN
    build:
      dockerfile: ./Dockerfile
      context: ./dnsmasq
    network_mode: host
    environment:
      - PRIVATE_IP=${PRIVATE_IP:-10.1.0.1}
      - PRIVATE_INTERFACE=${PRIVATE_INTERFACE:-lo}
      - SUBNET_START=${SUBNET_START:-10.1.0.100}
      - SUBNET_END=${SUBNET_END:-10.1.255.255}
      - SUBNET_NETMASK=${SUBNET_NETMASK:-255.255.0.0}
      - DOMAIN=${DOMAIN:-progcont}
      - DNS_RESOLVER=${DNS_RESOLVER:-1.1.1.1}
      - STATIC_LEASES=${STATIC_LEASES:-}
    volumes:
      - ./dnsmasq/dnsmasq.conf.template:/etc/dnsmasq.conf.template
      - ./pxe:/pxe
      - ./dnsmasq/dnsmasq.leases:/var/lib/misc/dnsmasq.leases

  user-data:
    image: alpine/curl
    volumes:
    - ./pxe:/pxe
    command:
      - /bin/sh
      - -c
      - |
        set -o pipefail && 
        cat<<"EOT">/pxe/user-data
        #cloud-config
        autoinstall:
          version: 1
          drivers:
            install: true
          proxy: http://_gateway:3142
          kernel:
            flavor: hwe
          shutdown: reboot
          identity:
            hostname: ${MACHINE_HOSTNAME:-machine}
            password: ${MACHINE_PASSWORD:-'$2a$12$6EyKyPDuHQcHIF7Abawva.pCLQhGs0r/3NybeiMVgaKTDPbm.a7b6'}
            realname: ${MACHINE_USERNAME:-contestadmin}
            username: ${MACHINE_USERNAME:-contestadmin}
          storage:
            grub:
              reorder_uefi: true
              update_nvram: true
              reorder_uefi_force_fallback: true
            config:
              # disk
              - type: disk
                id: disk-sda
                ptable: gpt
                wipe: superblock-recursive
                name: ''
                preserve: false
                grub_device: true

              # physical partitions
              - type: partition
                id: partition-0
                number: 1
                device: disk-sda
                size: 1GB
                flag: boot
                grub_device: true
                preserve: false

              - type: partition
                id: partition-1
                number: 2
                size: -1
                wipe: superblock
                device: disk-sda
                preserve: false

              # lvm
              - type: lvm_volgroup
                id: lvm_volgroup-0
                name: ubuntu-vg
                devices:
                  - partition-1
                preserve: false

              - type: lvm_partition
                id: lvm_partition-0
                size: -1
                name: ubuntu-lv
                volgroup: lvm_volgroup-0
                wipe: superblock
                preserve: false

              # formats
              - type: format
                id: format-0
                fstype: vfat
                volume: partition-0
                preserve: false

              - type: format
                id: format-1
                fstype: ext4
                volume: lvm_volgroup-0
                preserve: false

              # mounts
              - type: mount
                id: mount-0
                path: /boot/efi
                device: format-0

              - type: mount
                id: mount-1
                path: /
                device: format-1
          ssh:
            allow-pw: false
            install-server: true
            authorized-keys:
        EOT
        echo "${GITHUB_USERNAMES:-tuupke}" | tr "," "\n" | (xargs -I{} curl -Sf https://github.com/{}.keys | sed -e 's/^/    - /') >>/pxe/user-data 
