services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/configure.sh:/docker-entrypoint.d/99-geproxy-config.sh
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - "${PRIVATE_IP:-10.1.0.1}:80:80"
      - "${PRIVATE_IP:-10.1.0.1}:443:443"
    depends_on:
      devdocs:
        condition: service_started
    environment:
      - CCS_HOST=${CCS_HOST:-https://judge.gehack.nl}
      - CONTEST_HASH=${CONTEST_HASH:-contest_hash}
      - SSL_CERT_LOC=${SSL_CERT_LOC:-}
      - SSL_KEY_LOC=${SSL_KEY_LOC:-}
      - DOMAIN=${DOMAIN:-progcont}
    cap_add:
      - NET_ADMIN

  devdocs:
    image: geproxy/devdocs
    build:
      dockerfile: ./Dockerfile
      context: ./devdocs
    environment:
      - LANGUAGES="${LANGUAGES:-'openjdk@17 c cpp python@3.10'}"

  dnsmasq:
    image: geproxy/dnsmasq
    cap_add:
      - NET_ADMIN
    build:
      dockerfile: ./Dockerfile
      context: ./dnsmasq
    network_mode: host
    environment:
      - PRIVATE_IP=${PRIVATE_IP:-10.1.0.1}
      - PRIVATE_INTERFACE=${PRIVATE_INTERFACE:-lo}
      - SUBNET_START=${SUBNET_START:-10.1.0.100}
      - SUBNET_END=${SUBNET_END:-10.1.255.255}
      - SUBNET_NETMASK=${SUBNET_NETMASK:-255.255.0.0}
      - DOMAIN=${DOMAIN:-progcont}
      - DNS_RESOLVER=${DNS_RESOLVER:-1.1.1.1}
      - STATIC_LEASES=${STATIC_LEASES:-}
    volumes:
      - ./dnsmasq/dnsmasq.conf.template:/etc/dnsmasq.conf.template
      - ./dnsmasq/dnsmasq.leases:/var/lib/misc/dnsmasq.leases

