services:
  traefik:
    build:
      context: ./traefik
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.file.filename=/etc/traefik/dynamic.yaml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "${PRIVATE_IP}:80:80"
      - "${PRIVATE_IP}:443:443"
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - ./traefik/certs:/etc/traefik/certs:ro
    env_file:
      - .env
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/configure.sh:/docker-entrypoint.d/99-geproxy-config.sh
  #     - ./nginx/conf.d:/etc/nginx/templates
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   ports:
  #     - "${PRIVATE_IP:-10.1.0.1}:80:80"
  #     - "${PRIVATE_IP:-10.1.0.1}:443:443"
  #       #depends_on:
  #       #  devdocs:
  #       #    condition: service_started
  #   environment:
  #     - CCS_HOST=${CCS_HOST:-https://judge.gehack.nl}
  #     - CONTEST_HASH=${CONTEST_HASH:-contest_hash}
  #     - SSL_CERT_LOC=${SSL_CERT_LOC:-}
  #     - SSL_KEY_LOC=${SSL_KEY_LOC:-}
  #     - DOMAIN=gehack.nl
  #   restart: unless-stopped
  #   cap_add:
  #     - NET_ADMIN

#  squid:
#    image: luukblankenstijn/squid:latest
#    network_mode: host
#    cap_add:
#      - NET_ADMIN
#      - NET_BIND_SERVICE
#      - NET_RAW
#      - SETPCAP 
#    volumes:
#      - ./squid/squid.conf:/etc/squid/squid.conf:ro
#      - ./squid/certs:/etc/squid/certs:ro
#      - ./squid/allowlist.txt:/etc/squid/allowlist.txt:ro
#      - squid-cache:/var/cache/squid
#      - squid-logs:/var/log/squid
#    restart: unless-stopped
#    command: ["/usr/sbin/squid", "-N", "-d", "1"]

   

  dnsmasq:
    image: geproxy/dnsmasq
    cap_add:
      - NET_ADMIN
    build:
      dockerfile: ./Dockerfile
      context: ./dnsmasq
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./dnsmasq/dnsmasq.conf.template:/etc/dnsmasq.conf.template
      - ./dnsmasq/dnsmasq.leases:/var/lib/misc/dnsmasq.leases

volumes:
  squid-cache:
  squid-logs:
