http_port 3128 intercept
https_port 3129 tproxy ssl-bump cert=/etc/squid/certs/squid.combined.pem

http_port 3127
http_access deny all

visible_hostname squid-proxy
pid_filename /var/run/squid/squid.pid
coredump_dir /var/cache/squid

acl step1 at_step SslBump1
acl allow_sni  ssl::server_name "/etc/squid/allowlist.txt"
acl allow_http dstdomain "/etc/squid/allowlist.txt"

ssl_bump peek step1
ssl_bump splice allow_sni
ssl_bump terminate all

http_access allow allow_http
http_access deny all

logformat bump %ts.%03tu %>a %ssl::>sni %ssl::bump_mode %>Hs %rm %ru
access_log stdio:/var/log/squid/access.log bump
access_log stdio:/var/log/squid/access.log
