---
- name: Disable internet
  gather_facts: false
  hosts: all
  become: yes
  vars_files:
    - ../defaults.yaml
    - ../config.yaml
    - ../config.yml
  handlers:
    - name: Apply sysctl config
      ansible.builtin.command: "sysctl -p"
    - name: Stop ip-forwarding in /etc/sysctl.conf
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^\s*net.ipv4.ip_forward\s*=\s*1'
        line: net.ipv4.ip_forward=0
      notify:
        - Apply sysctl config
  tasks:
    - name: Discover public interface
      ansible.builtin.shell: ip r | awk '/^default/ {print $5}'
      register: public_interface_cmd

    - name: Set public interface
      ansible.builtin.set_fact:
        public_interface: "{{ public_interface_cmd.stdout }}"

    - name: Disable forwarding from private to public
      ansible.builtin.iptables:
        state: absent
        chain: FORWARD
        in_interface: "{{ private_interface }}"
        out_interface: "{{ public_interface }}"
        jump: ACCEPT
    
    - name: Disable forwarding from pulic to private
      ansible.builtin.iptables:
        state: absent
        chain: FORWARD
        in_interface: "{{ public_interface }}"
        out_interface:  "{{ private_interface }}"
        match: state
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT

    - name: Disable nat
      ansible.builtin.iptables:
        state: absent
        table: nat
        out_interface: "{{ public_interface }}"
        chain: POSTROUTING
        jump: MASQUERADE
      notify: Stop ip-forwarding in /etc/sysctl.conf
